title: Anthony Cherepanov | Web development
description: Anthony Cherepanov. CEO at Hype.codes | Business Development at evrone.com
keywords: ruby, rails, ruby on rails, javascript, node, aws, devops, engineer, mentor
markdown: redcarpet
