title: Antony Cherepanov | Web development
description: Antony Cherepanov, Business Development Executive at evrone.com
keywords: ruby, rails, ruby on rails, javascript, node, aws, devops, engineer, mentor
markdown: redcarpet
