title: Antony Cherepanov | Singula.team founder
description: Antony Cherepanov, CEO at singula.team
keywords: ruby, rails, ruby on rails, javascript, node, aws, devops, engineer, mentor
markdown: redcarpet
