title: Anton Cherepanov | Full Stack Engineer
description: Anton Cherepanov. Full Stack Engineer. Ruby/Rails/JS mentor
keywords: ruby, rails, ruby on rails, javascript, node, aws, devops, engineer, mentor
markdown: redcarpet
